name: qtquick
channels: !!python/tuple
- defaults
dependencies:
- cycler=0.10.0=py35_0
- icu=57.1=vc14_0
- jpeg=8d=vc14_2
- libpng=1.6.22=vc14_0
- matplotlib=1.5.3=np111py35_1
- mkl=11.3.3=1
- numpy=1.11.2=py35_0
- openssl=1.0.2j=vc14_0
- pip=9.0.0=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- qt=5.6.0=vc14_0
- setuptools=27.2.0=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- tk=8.5.18=vc14_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- zlib=1.2.8=vc14_3
prefix: C:\Anaconda3\envs\qtquick

